apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
  labels:
    app: postgresql
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
